### ISSUE TITLE
All Archives template - inherit query from template

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/raft#107]
A user reported this through email, and looks like we can fix this easily. The issue is that the query block, should inherit the template query, since it is part of the template. The fix is simple, need to add the `"inherit":true` in the block's meta. I will make a PR.

**📌 UPDATE:** Looks like a false alarm, I got confused because I looked at the demo, which had a customised  template I was working with, after checking the master files, the query blocks are configured properly I will wait to see if client has any feedback (he was experiencing some issues with the query), and might close this issue.

![inherit](https://github.com/Codeinwp/raft/assets/4193672/08c6f524-07a1-4e35-a246-d248926ae488)

**Comment by HardeepAsrani** [comment]
It is the case already as you pointed out in your update: https://github.com/Codeinwp/raft/blob/master/templates/archive.html#L19
