### ISSUE TITLE
Raft is only pulling the in built Homepage not the one that we have selected

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/raft#11]
### Description
Some users on the WP forum reported that-

When we activate the Raft theme then there is no option to change the Homepage of the theme. If you have previous content on the site then you won't be able to use the previous homepage or the content either

### How to replicate
1. Install Neve/Hestia and import the demo template so that you will have a designed homepage with some content.
2. Install Raft and visit the site you will observe that there is a static homepage(Block based website made simple) on the site which comes inbuilt with Raft.
3. Go to Settings > Reading, select a different page or try selecting the latest posts option.
4. Observe that no change has occurred in both conditions.
5. Now for the second issue, go to pages --> edit the home page --> you will see all the previous content here.
6. View this home page using the preview option, you will see the same page again.
7. Try to do the same thing with other Full site editing themes like twenty twenty-two.
8. You won't face such issues.

### Reference
![image](https://user-images.githubusercontent.com/110405452/196783209-e36a4e95-2631-4602-8698-435d4459d526.png)
![image](https://user-images.githubusercontent.com/110405452/196783337-76e5691f-5388-4423-b901-efd7c8bb2faa.png)
Screencast:
1st issue: https://vertis.d.pr/v/57GxCI
2nd issue: https://vertis.d.pr/v/hmVx3X

### Technical info

WP version- 6.0.3
Raft version - v1.0.3

**Comment by kushh23** [comment]
P.s-   https://wordpress.org/support/topic/home-page-content-not-the-same-as-in-edit-mode/

**Comment by JohnPixle** [comment]
Sorry for the late reply on this.

I understand the issue here, and it might be indeed confusing for the average user. @abaicus what do you think about not having a Front Page template at all? For our demo, we can replicate the layout in a static page, and set it as Homepage in Reading Settings. 

I don't see how adding the content block would solve the problem tbh, I think it might lead to more confusion, since -even with the page content visible on the homepage- the user will still need to edit the rest Homepage parts in the FSE editor (in order to customise the content etc.)

So, my suggestion would be to:

- Remove the homepage template
- Register the existing homepage sections as patterns (we have similar ones already, but not all of them)
- Create a static page with the same layout, but we will set it as the homepage under Reading Settings in the demo.

I think this is the simplest way to meet the expectations of most users. 

If we expect them to be fluent enough to add the content block by editing the current homepage template, they should be able to create a  custom homepage template as well if they want to.

Let me know what you think about that, and if you see any possible drawbacks.

Thanks!

**Comment by abaicus** [comment]
@JohnPixle I think that removing the front page could work - we already have everything as patterns: 

```html
<!-- wp:template-part {"slug":"header","tagName":"header","theme":"raft"} /-->

<!-- wp:pattern {"slug":"raft/hero"} /-->

<!-- wp:pattern {"slug":"raft/three-columns-features"} /-->

<!-- wp:pattern {"slug":"raft/call-to-action"} /-->

<!-- wp:template-part {"slug":"footer","theme":"raft","tagName":"footer"} /-->
```

The problem with that is that it's not going to show up in the WP.org preview anymore.

**Comment by JohnPixle** [comment]
@abaicus  Hm... what if we use a static page for the homepage (and set this page as homepage under Settings \ reading), and replicate the same exact design using patterns? Wont this work?

**Comment by abaicus** [comment]
Unfortunately not. We don't have access to what is displayed on the WP.org preview. We can't change that in any way. It defaults to how the theme looks on a clean website.

I'm talking about the preview here: https://wordpress.org/themes/raft/

**Comment by JohnPixle** [comment]
@abaicus Ah, what a bummer! I understand what you mean, It would behave like https://wordpress.org/themes/twentytwentytwo/ where when you switch Style Variations, the variations are previewed on a blank page

![Screenshot 2022-10-31 at 13 56 13](https://user-images.githubusercontent.com/4193672/199002437-a662e936-13e2-4139-9685-1d9cbe7e7459.png)

--- 

However, can we still keep a proper homepage image for the default variation? Like they do for TT2 ?

---



![Screenshot 2022-10-31 at 13 56 31](https://user-images.githubusercontent.com/4193672/199002520-b8c9bbfd-de72-436b-a3f8-e6edea8047a9.png)

**Comment by abaicus** [comment]
@JohnPixle Exactly! 👍🏻 

The thing is that I feel that this could be better if we add the page content under the hero. It's more about the FSE paradigm core adopted that is confusing. Having a page without the content block is a valid approach, IMHO. 

Think about other themes we have/had, like Hestia, Zelle, etc. that had a template for the front page, and that template had an optional content section (in Hestia it's the About section, I believe).

There are other FSE themes in the repository doing this. 

At least having the content block on the front page template might give the user a better hint about what is happening.

**Comment by JohnPixle** [comment]
@abaicus Yeah, I tend to agree with you actually, makes sense. Okay, I will do the change in the theme demo and let you know. I will add it right below the hero.

**Comment by abaicus** [comment]
@JohnPixle Thanks for your help on this! 🚀

**Comment by JohnPixle** [comment]
@abaicus I have made the change at the homepage template. It's the [Raft demo](https://demosites.io/raft/). Here is some context:

### 1. Post content block
At the homepage template I added a group with the post content block below the hero area.

![Screenshot 2022-11-01 at 11 32 28](https://user-images.githubusercontent.com/4193672/199203829-2f6ec411-b063-4bc7-8a10-3713ca4678d4.png)

### 2. New page for homepage content
For the demo purposes, I created [a new page](https://demosites.io/raft/wp-admin/post.php?post=61&action=edit) and added the patterns we used to have in the original homepage template. I have set this page as the homepage under reading settings.

![Screenshot 2022-11-01 at 11 34 18](https://user-images.githubusercontent.com/4193672/199204164-15059894-9e77-4f8e-996a-3dd35a8ff93d.png)

I think the above setup makes sense, and users should be able to output the content in the homepage without getting overly confused. Let me know if this works, happy to help wherever needed.

**Comment by abaicus** [comment]
@JohnPixle, for the demo site, this makes sense. 

Unfortunately, we cannot control what is displayed on the WordPress.org preview. If we remove the blocks in the front page template, they won't appear in the preview; essentially, the front page will have less content in the WP preview. My suggestion is to add a content block somewhere in between the current sections we have.

**Comment by JohnPixle** [comment]
@abaicus ok got it. So you suggest adding a section like this? (screenshot below). 

I added the block content inside a section that respects our current layout. So if users add some  content, it will display with proper spacing regarding the rest of the page.

Let me know if it makes sense.

![Screenshot 2022-11-21 at 4 31 57 PM](https://user-images.githubusercontent.com/4193672/203080649-06e6169b-982d-495d-8f1d-7b6e64358d74.png)

the html for this section is

```
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"64px","bottom":"64px"},"margin":{"top":"0px","bottom":"0px"}}},"layout":{"inherit":false,"wideSize":"960px"}} -->
<div class="wp-block-group alignfull" style="margin-top:0px;margin-bottom:0px;padding-top:64px;padding-bottom:64px"><!-- wp:post-content /--></div>
<!-- /wp:group -->
```

I can add it inside our existing template if you point me to the file 😇

**Comment by abaicus** [comment]
Exactly! That works fine 👍🏻 I'll add it to the template.
