### ISSUE TITLE
Use different Font families in each style variation

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/raft#12]
Hey @abaicus, this to follow-up from our discussion on Slack.

So, as mentioned there, the idea is to explore the option of adding different font families for each Style Variation we offer. 
[TT3](https://wordpress.org/themes/twentytwentythree/) does something similar and it manages to express a completely different aesthetic for each variation. I was wondering if we can do something along these lines.

### Backwards compatibility
I am not sure if it will be ok to change the font families on the existing style variations, in terms of compatibility with existing users. For users who already use style variation from Raft, it would be too intrusive to change the font families that are being used with that variation. I am not sure what would be the best approach for this.

In my opinion, we already have enough style variations, so it would be preferable to be able to inject the new font families in these existing variations. Other wise, we can keep the existing ones with the existing font, and see if we can create new ones with different fonts.

### Next steps
What would be the best approach moving forward?
To help things get started, I can provide you some Font families that I believe would work well. Let me know if it will be enough for this phase. I can definitely provide more details if needed (Font Sizes, line heights etc) but I believe we can try to keep things on a basic level, at least for the beginning.

Let me know your thoughts.

**Comment by JohnPixle** [comment]
I have done [3 proposed Style variations](https://www.figma.com/file/VWdtrtLP9zKaMHwYxV1GBl/Raft?node-id=404%3A1149) with different fonts families and colors.  I'll wait for your signal and proceed to more detailed specifications as needed.

Currently the Font families used in the mockups are:

Figtree
Source Serif Pro
Outfit

Each color variation uses the same Font family for both Headings and Text.



![Screenshot 2022-11-07 at 11 55 16 AM](https://user-images.githubusercontent.com/4193672/200281308-7c281ae7-7446-4430-93e1-ed6682e5ecb3.png)

**Comment by abaicus** [comment]
@JohnPixle I just checked this, and there's no issue if we overwrite font families in style JSON files we already have in the theme. Once a user selects a style, it's saved in the DB with its' current state. Unless the user goes into the style-switcher again to reselect it, nothing happens to the website. 

---

My main concern now is the way we initially added the font families. I thought it was a good idea to use Body/Headings for the font families, but it seems that core has a different approach. I.e., twentytwentythree lists them as individual font families:

![image](https://user-images.githubusercontent.com/15010186/201943434-8cb973e3-afdc-4298-89c2-eb8fda1f7a8a.png)


A good idea might be following in the same path as they do. What's your take on this? 

Thanks! 🚀

**Comment by JohnPixle** [comment]
> Unless the user goes into the style-switcher again to reselect it, nothing happens to the website.

@abaicus thats great actually, really happy to hear that 😃.

What I can do then is to provide some font families / variations to assign as new defaults to some of our existing color variations. I'll find a way to provide those to you in a tidy way here on GH.

> My main concern now is the way we initially added the font families. I thought it was a good idea to use Body/Headings for the font families, but it seems that core has a different approach. I.e., twentytwentythree lists them as individual font families

I do believe this core approach might be more flexible tbh.
I'd say we can try it, if it's not a big breaking change.

**Comment by JohnPixle** [comment]
@mghenciu Good job on the patterns 👍🏻 . Simple enough  and safe across themes and styles.

At the bottom of the page I have just added a section with Circular Progress Bars, and one version of the Review pattern with plain background. As a general advice let's avoid to use patterns that have many inline colors on the blocks / sections. So far I only noticed it on your inverted review pattern, so that's why I am giving you a heads-up 🙃.

Feel free to keep my added patterns or remove / edit them as you see fit.

Your consideration about the posts block is very valid, let's see what Hardeep has to say about that, because I have a feeling that it will not work as expected in the preview. Hopefully I am wrong, but it's worth testing.

I think you can give it a try already by using a plugin like this: https://wordpress.org/plugins/custom-block-patterns/ by saving a pattern with a blog posts block and preview it in the sidebar.

Let me know if you need any help overall with this!

**Comment by JohnPixle** [comment]
I have done some further work on the Font and and style variations, let me know when you are ready to get started on this.

### Existing Styles

| Style Variation        | Font           | 
| ------------- |:-------------:| 
| Default      | Readex Pro |
| Apple clean      | Readex Pro      |
| Blue Retro | Readex Pro      |
| Clean cut | Readex Pro      |
| Garden flow | Source Serif Pro      |
| Green corn | Readex Pro      |
| Night owl | Outfit      |
| Purple dawn | Figtree      |

### New Styles

Here are [4 new style variations](https://www.figma.com/file/VWdtrtLP9zKaMHwYxV1GBl/Raft?node-id=415%3A1148&t=TGXulFM7sAv2w4ig-1), I will follow up for the Theme colors.

| Style Variation        | Font           | 
| ------------- |:-------------:| 
| Blue cream      | Figtree |
| Light serif      | Source serif Pro |
| Dark fit      | Outfit |
| Wooden     | Lora |

**Comment by JohnPixle** [comment]
@abaicus here are the colors for the 4 new style variations. I hope the format is ok for you. Let me know if you need any help or clarifications with these!

| Style Variation   | Background  | Foreground  | Background alt  | Foreground alt  | Accent  | 
| ------------- |:-------------:| :-------------:| :-------------:| :-------------:| :-------------:| 
| Blue cream      | `#FFF0E9` | `#202220` | `rgba(255, 255, 255, 0.3)` | `#FFFFFF` | `#2A359E` |
| Light serif      | `#DFE2ED` | `#202020` | `rgba(255, 255, 255, 0.3)` | `#FFFFFF` | `#202020` |
| Dark fit      | `#1B1818` | `#FFFFFF` | `rgba(255, 255, 255, 0.05)` | `#FFFFFF` | `#417E61` |
| Wooden     | `#EFECE7` | `#202020` | `rgba(255, 255, 255, 0.5)` | `#FFFFFF` | `#544636` |

**Comment by abaicus** [comment]
@JohnPixle, thank you for providing these! 🚀 I've added the styles. They should become available in [this PR](https://github.com/Codeinwp/raft/pull/17) after the zip file is built. 👍🏻
