### ISSUE TITLE
Add new patterns

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/raft#15]
https://demosites.io/raft/patterns-update/

@JohnPixle Keeping you in the loop. Just adding this here so we can track things. 👍🏻

**Comment by abaicus** [comment]
@JohnPixle Yes, the process is correct. There's one more thing you need to do for this to work. You must add the filename without extension here: https://github.com/Codeinwp/raft/blob/master/inc/Block_Patterns.php#L65-L76.

If you need any help, let me know!

Another thing to remember is that we should not add strings with the new patterns. We can try reusing some that we already have in other patterns. 

Also, we have to provide images from the patterns in the theme, similar to how we already do it in existing patterns. 

If you want, we can simplify the process. You can simply add the patterns in some `.html` files and I can handle converting and adding everything afterward. 👍🏻

**Comment by JohnPixle** [comment]
Thanks @abaicus!

I will be honest, I think I will just add the content HTML files and share them with you. I am pretty sure I would mess something up. 

I will do the same for the extra template parts I created (header footer). 
Will keep you updated!

**Comment by JohnPixle** [comment]
@abaicus I am back with the new patterns HTML files. 
Had to do a bit more testing and make sure they worked well on all style variations and I adjusted a couple of risky ones.

Here is the zip containing 11 htmls:

[patterns.zip](https://github.com/Codeinwp/raft/files/10041433/patterns.zip)

As a reminder, the updated patterns are also live on this page: https://demosites.io/raft/patterns-update/

### Template parts
I also created two template parts, one header and one footer. The zip below contains them both.

[template parts.zip](https://github.com/Codeinwp/raft/files/10041437/template.parts.zip)


Here is a screenshot for a visual reference for them. I am not sure happy with them to be honest, there are limitations in the responsiveness (especially for the header) so this is the best I could come up with. 

![Screenshot 2022-11-18 at 3 05 05 PM](https://user-images.githubusercontent.com/4193672/202712160-2cd9830a-eb76-4ea5-b343-5e34b24567ca.png)

![Screenshot 2022-11-18 at 3 05 24 PM](https://user-images.githubusercontent.com/4193672/202712169-85a75de5-5a5e-4f99-aa1b-1d41d237c70d.png)

I will follow up with templates for Singles and Archives.

Please keep me in the loop in case you face any issues, need any clarifications or help in general.

Thanks! 🚀

**Comment by abaicus** [comment]
@JohnPixle, Is there a chance I can get as SVG all the images used in the new patterns, please? We did this for the initial patterns, so everything will look crisp.

**Comment by abaicus** [comment]
Also, I just noticed that the lightbulb icon seems to have a small issue on the left side of the filament: 
![image](https://user-images.githubusercontent.com/15010186/203066258-7fa0e8cf-f8e5-4539-a8dc-2a5848ee2fa4.png)

**Comment by JohnPixle** [comment]
@abaicus So sorry about that 😟. I dont know why, but I was under the impression that we were using pngs, and I actually wanted to suggest the use of SVG. Dont know why I got confused. Anyway.

Many of the images I used for the new patterns were already included in the old patterns, I see the assets here: https://github.com/Codeinwp/raft/tree/master/assets/img. 

Give me a few minutes and I will get you the extra ones with consistent file naming as the old ones.

**Comment by abaicus** [comment]
We use SVG-s in the patterns, but the user can't natively upload SVG files to WP. I think that's probably the reason for the confusion 👍🏻

**Comment by JohnPixle** [comment]
@abaicus  Yeah, probably. Anyway, I exported any new images used in the patterns, in SVG. Attaching the zip here.
[newSVGs.zip](https://github.com/Codeinwp/raft/files/10057254/newSVGs.zip)


In case it helps, I am also attaching this screenshot from Figma which gives an overview of old vs new images.

![Screenshot 2022-11-21 at 4 17 21 PM](https://user-images.githubusercontent.com/4193672/203077755-9abb63cd-7a11-499c-84e9-e5c11af0482f.png)

Let me know if this helps. I am around in case I can do something to make things easier for you in the process.
