### ISSUE TITLE
Category pages shows posts from all categories

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/raft#23]
### Description

In the Raft theme each category/archive page shows posts from all categories instead of showing posts that belong to that category only.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/36594177/219787015-89259597-c656-4336-b8c3-ec14e5224151.png">

Existing categories: 
<img width="981" alt="image" src="https://user-images.githubusercontent.com/36594177/219787172-9be213ac-1380-4591-b190-302b5845808a.png">

If I switch to another theme like Riverbank it shows correctly:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/36594177/219787328-4470f345-05b2-4ec6-9d13-c768fa7aa768.png">

Reported here - https://wordpress.org/support/topic/categories-show-all-posts-regardless-of-category/

### Step-by-step reproduction instructions

1. Create a few posts and assign then to different categories.
2. Visit one of the categories in the front-end.
3. You'll see all posts on category/archive page, not only those that belong to category.

### Environment info

https://pastebin.com/S3VpAeSW

### Is the issue you are reporting a regression

No

**Comment by blender-hub** [comment]
Hopefully this gets fixed soon, it doesn't seem big, but it would make a MASSIVE difference.

**Comment by HardeepAsrani** [comment]
Hey @blender-hub, while we release this fix, you can edit the Archive template and use the checkbox for "Inherit query from template" and it should start working properly.

<img width="1623" alt="Screenshot 2023-03-03 at 11 10 58 AM" src="https://user-images.githubusercontent.com/2649903/222640693-429f6305-92a7-46b4-8e6d-a4ffe708e811.png">
