### ISSUE TITLE
Some of the Typography customizations won't appear

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/raft#24]
### Description

I was testing the typography of the buttons, but some of the customizations doesn't apply. For example, the size won't load, except for the preview where it works, also the Appearance of the letters is not working for most of the cases, except for Bold, Italic, and normal.

### Step-by-step reproduction instructions

1. Install Raft and open the editor
2. Go to styles and choose typography
3. click on buttons and start making changes

### Screenshots, screen recording, code snippet or Help Scout ticket

https://www.loom.com/share/7da488f583fb478b96d7498b015ba195

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
So Raft does not add any functionality to the Styles panel. All the options are from Core.

I tasted it on a local instance, and both Raft and WP Default Theme behave the same. No issue was found.

But when I made an instance on WP Taste. The issues from your video surfaced on both Raft and WP Default Theme in the same manner.

I suspect it might be related to hasting, in this case, WP Taste.

@AndreeaCristinaRadacina, can you confirm this by trying to use another hosting provider at your disposal?

**Comment by Soare-Robert-Daniel** [comment]
@AndreeaCristinaRadacina feel free to close this issue.

Not all the options for typography are supposed to work. It depends a lot on the type of font loaded, and the theme may have different Font Types.
Examples:

Spectra One

https://user-images.githubusercontent.com/17597852/230595382-aaa6dca8-1d73-49a3-8ee3-e2e868aa9b53.mp4

Default WP 2023

https://user-images.githubusercontent.com/17597852/230595499-caac4917-d106-4961-86f5-fdd1d01fd565.mp4

**Comment by AndreeaCristinaRadacina** [comment]
@Soare-Robert-Daniel okay, thank you for taking a look!
