### ISSUE TITLE
Wordpress 6.2 compatibility

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/raft#35]
### Description

Wordpress 6.2 is scheduled to be released on March 28 and we can test it since RC1 is out 

Here is a list of the upcoming changes:
(There are some FSE changes so we should also test Riverbank, Jaxon, Fork)
https://www.wpbeginner.com/news/whats-coming-in-wordpress-6-2-features-and-screenshots/

**Comment by irinelenache** [comment]
Tested and didn't find any problem with the WP 6.2 compatibility 🚀 

cc @HardeepAsrani

**Comment by HardeepAsrani** [comment]
Thank you @irinelenache for looking over this.
