### ISSUE TITLE
Caption color doesn't apply as it's overwritten

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/raft#56]
### Description

When using an image with a caption, it is possible by editing Styles -> Colors to set a custom color for the caption.

The color set doesn't apply as it's overwritten by another value.

### Step-by-step reproduction instructions

1. On a sample page, add an image with caption and type something in there
2. Open the site editor and navigate to Styles -> Colors
3. Edit the colors and set a custom color for the caption
4. Visit the page and see that neither in the editor or on the front end the caption color applies

### Screenshots, screen recording, code snippet or Help Scout ticket

![styles](https://github.com/Codeinwp/raft/assets/26867648/628db036-1751-4764-a8de-d708bbc2a5f5)
![caption-in-console](https://github.com/Codeinwp/raft/assets/26867648/ff5aa6ab-3c4d-4e91-9a9b-d246d67d4338)

Reported here: https://wordpress.org/support/topic/posible-bug-limited-caption-customisation-in-raft-theme/#post-17019590

### Environment info

https://pastebin.com/Xgeq8Cam

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@JohnPixle I was looking into it, and it looks like now the theme.json allows us to style captions. I was thinking, we can probably move all the styling of caption that is possible from CSS to theme.json

Let me know your thoughts.

**Comment by HardeepAsrani** [comment]
@JohnPixle I'd still be happier with a bigger theme.json than CSS files as users can customize things that are part of theme.json but overriding custom CSS might be tricky for people.
