### ISSUE TITLE
Re-organise Pattern Library

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/raft#61]
### What problem does this address?

In the pattern library, we want to provide a theme-tight experience regarding patterns and page layouts. Currently in our themes, we follow the default/core pattern folder structure, and we also include many of the core patterns, which are inconsistent with the styles and layout of our theme. 

Additionally, we now keep our theme patterns in their own folder, which does not help with discoverability and workflow integration. 

![current](https://github.com/Codeinwp/raft/assets/4193672/43350a40-29fb-41da-88dc-9acb280c14d8)

### What is your proposed solution?

In order to create a safe and efficient environment for our users, we can:

- Remove the core patterns from the pattern library
- Organise the library with appropriate folders
- Distribute Theme patterns to these categories

![new](https://github.com/Codeinwp/raft/assets/4193672/f9550ba7-781b-4ba4-95f4-336fb4e9e1ce)

This issue is also aligned with [Neve FSE library](https://github.com/Codeinwp/neve-fse/issues/89) direction
Also, let's keep in mind how this enriched library experience will interplay with the onboarding wizard.

cc @mghenciu 

### Will this feature require documentation? (Optional)

None

**Comment by HardeepAsrani** [comment]
@JohnPixle You can find the PR here: https://github.com/Codeinwp/raft/pull/71

Here you can find all the registered patterns in case you want to make any modifications to their title/slugs: https://github.com/Codeinwp/raft/pull/71/files#diff-b2ab93a7ea5192f0e9924b2d8d3afe199235614e83100664ca7b451f944af6baR60

And the patterns will currently show up in Uncategorized as we need to assign them to appropriate categories. Let me know if you have a list so I could do that or you'd be doing it as you create new patterns.
