### ISSUE TITLE
Create new patterns and page layouts

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/raft#62]
Since we are going to re-organise the library in #61 we need to create additional design material to populate these folders.

We need 
- 5-7 full-page layouts. These will go into the "Pages" folder in sidebar
- 3-5 patterns minimum for each category. If existing pattern material is not sufficient, we need to enrich the collection.

**Comment by mghenciu** [comment]
@JohnPixle , have you started any work for this?
And do we have a deadline for it/the milestone release date?
