### ISSUE TITLE
Add new site template: Fullwidth with Header and Footer

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/raft#79]
Currently, apart from the default page template that has a fixed content width,  we have a fullwidth template (blank) that displays only the content, without the header and footer. But we don't have a full-width template that users can use with header and footer parts. This is quite useful, and I suggest we add this efficiency.

@HardeepAsrani This is the content for this template, let me know if it looks good and if you have any questions. If it does, feel free to register this in the theme. 

```
<!-- wp:group {"style":{"spacing":{"margin":{"top":"0","bottom":"0"},"padding":{"top":"0","bottom":"0","left":"0","right":"0"},"blockGap":"0"}},"layout":{"inherit":false}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:post-content {"layout":{"type":"constrained","contentSize":"100%"}} /--></div>
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","theme":"raft","tagName":"footer"} /-->
```

**Comment by HardeepAsrani** [comment]
@JohnPixle Not sure if it's intended or not but in your code, I don't see the header. That's a mistake, right?
