### ISSUE TITLE
Integrate NPS Feedback

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/raft#84]
@HardeepAsrani For this release, we will also need to integrate the NPS survey from FormBricks, in order to be able to collect Feedback from users.
There is an existing Survey created [at FormBricks](https://app.formbricks.com/environments/clp9hp3j71oqndl2ietgq8nej/surveys/clp9hpl3n1or1dl2iw6zurgn8/edit), but we need to [integrate it](https://app.formbricks.com/environments/clp9hqm8c1osfdl2ixwd0k0iz/settings/setup).

Let me know if I can help in any way with this!

**Comment by HardeepAsrani** [comment]
Hey @JohnPixle,

About this and https://github.com/Codeinwp/otter-internals/issues/124, I just wanted to ask you when exactly do we display the form? Do we need to define some conditions in the products or those are already defined in the FormBricks?

Also, do we show this in particular screen or all over the Dashboard?
