### ISSUE TITLE
Otter Banner in admin after theme install

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/raft#89]
@HardeepAsrani Here is another one we must take care or this release. Let me know your thoughts on it when you have some time. 

Until now, when a new user installs and activates Raft, we show them the standard Otter banner. 

I suggest that we re-work this banner, and give it a more theme-specific touch, which also includes onboarding in the message. We can adapt the messaging and imagery in the future, when /if we integrate onboarding into our other FSE themes as well.

For now, this would only apply to Raft Theme. Our other FSE themes will display the current banner.

![Raft message](https://github.com/Codeinwp/raft/assets/4193672/0f137a07-d9c4-4dd0-a6c0-fcc9d81b19c1)

**Condition:** New Raft install and Otter is not active in the site.
**Behaviour:** When the Install button is clicked, we install and activate Otter and initiate the wizard.

[Figma File.](https://www.figma.com/file/pwDRauGhxiDFANvO7MeeNR/Otter-Onboarding?type=design&node-id=1702%3A1342&mode=design&t=7eI8YelSkuJpiFIf-1)

Here is the copy for the banner:

**Power-up your website building experience with Otter Blocks: Seamless theme setup, advanced blocks and extra functionality for your site.**

_Otter is a Gutenberg Blocks page builder plugin that adds new blocks and functionality to your theme, while optimising your page building experience. Now with Otter’s new theme onboarding wizard, you can experience a streamlined and intuitive setup of your Raft theme in minutes_.

**Comment by HardeepAsrani** [comment]
@JohnPixle can you send me the image file for there? Also, it will look the same in high screen sizes with text taking full space? Thanks!
